### ISSUE TITLE
Chrome 33.0.1750.117 m bug

### ISSUE THREAD

**Issue by no1lov3sme** [mqchen/jquery.diamonds.js#9]
Broken on Chrome version 33.0.1750.117 m.
Looks a bit better, by setting:

``` css
.diamond-row-upper, .diamond-row-lower {
    width: 101%;
}
```

but still does not fixes.
